# -*- coding: utf-8 -*-
"""aikit_demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zaOv9OuywSI9JqxLK7sGmDarc5Rbp5tB
"""

################################################################################
# INSTALL CONDA ON GOOGLE COLAB
################################################################################
! wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh
! chmod +x Miniconda3-py37_4.8.2-Linux-x86_64.sh
! bash ./Miniconda3-py37_4.8.2-Linux-x86_64.sh -b -f -p /usr/local
import sys
sys.path.append('/usr/local/lib/python3.7/site-packages/')

! source activate base

! conda create --name user_base --clone base

! conda update -n base -c defaults conda

! conda create -n aikit-modin -c intel intel-aikit-modin

! source activate aikit-modin

# Commented out IPython magic to ensure Python compatibility.
# %run aikit_xgboost_incidents.ipynb